language: python

python:
  - "3.4"

sudo: required

install:
  - sudo apt-get install guitarix
  - pip3 install coveralls

script:
  - coverage run --source=. setup.py test

after_success:
  - coveralls