language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "nightly"

sudo: required

jobs:
  include:
    - stage: doc
      script:
        - make install-docs-requirements
        - make docs

install:
  - make
  - sudo apt-get install -y portaudio19-dev python-all-dev --no-install-recommends
  - sudo apt-get install -y lilv-utils calf-plugins guitarix --no-install-recommends
  - pip3 install -U setuptools
  - make test

script:
  - pip3 install .
  - coverage3 run --source=application setup.py test

after_success:
  - bash <(curl -s https://codecov.io/bash)
