language: python

python:
  - "3.4"
  - "3.5"

sudo: required

before_install:
  - git submodule update --init --recursive

install:
  - pip3 install coveralls

script:
  - coverage3 run --source=architecture,controller,dao,model setup.py test

after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)
