language: python

python:
  - "3.4"

sudo: required

install:
  - sudo apt-get install guitarix
  - pip3 install coveralls

script:
  - coverage3 run --source=architecture,controller,dao,model,util setup.py test

after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)
